// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persona5APP.Models;

namespace Persona5APP.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Persona5APP.Models.Arcana", b =>
                {
                    b.Property<int>("arcanaID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Arcananame")
                        .IsRequired();

                    b.HasKey("arcanaID");

                    b.ToTable("Arcanas");
                });

            modelBuilder.Entity("Persona5APP.Models.Persona", b =>
                {
                    b.Property<int>("PersonaID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PersonaName");

                    b.Property<int>("arcanaID");

                    b.HasKey("PersonaID");

                    b.HasIndex("arcanaID");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Persona5APP.Models.Persona", b =>
                {
                    b.HasOne("Persona5APP.Models.Arcana", "arcana")
                        .WithMany("Personas")
                        .HasForeignKey("arcanaID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
